version: "3"

services:
      l2tp:
        image: siomiz/softethervpn
        restart: always
        ports:
          - 500:500/udp   # IPSEC IKE
          - 1194:1194/udp # OpenVPN data
          - 1194:1194/tcp # OpenVPN control
          - 1701:1701/udp # L2TP data
          - 1701:1701/tcp # L2TP control
          - 4500:4500/udp # IPSEC NAT-T data
        environment:
          - PSK=password
          - USERNAME=vpn
          - PASSWORD=password
        cap_add:
          - ALL


